### ISSUE TITLE
Factus snapshot deserialization is a fatal error although it doesn't have to

### ISSUE THREAD

**Issue by maciekpapiez** [factcast/factcast#1040]
**Describe the bug**
If Factus snapshot deserialization fails, then it's impossible to fetch the projection.

**FactCast Server/Client Version**
0.3.1

**To Reproduce**
Create an Aggregate projection, make Factus cache it, change the Aggregate projection in a non-compatible way (e.g. change type of a field), then try again to do `factus.fetch()`.

**Expected behavior**
If snapshot deserialization fails, then the snapshot is rebuild from scratch.

**Additional context**
n/a

**Comment by BernhardBln** [comment]
Nice to have: rather than having projections implement Serializable (and have developers remember to change the serial version id), maybe factcast can recognise itself if the class has changed and in that case discard the snapshot?

**Comment by uweschaefer** [comment]
Projections do not have to impl Serializable. The SerialVersionUID is supposed to be used to indicate if changes to the class make it incompatible with existing snapshots.
It would be nice to offload this decision to the JVM, but i don't know how to create the VM-assigned serialVersionUID without actually serializing it, but i did not take too much time investigating.

Any suggestions welcome.

Regarding the expected behavior: If Factus just recreates the aggregate from scratch it would certainly be convenient. However, the application is then no longer able to distinguish between restoring a snapshot and a freshly created one.
This (if going otherwise undetected) will lead to hard to diagnose performance problems.

I'd suggest to investigate creating an appropriate serialVersionUID if it is not set explicitly rather then hiding the error by falling back to recreating silently. Certainly, the documentation has to reflect that.  Volunteers?

**Comment by uweschaefer** [comment]
also, if you have two nodes working on different classes with the same sVUID, they would continuously destroy each others snapshots. i feel like failing fast is safer here...

Any other opinions?

**Comment by BernhardBln** [comment]
Summary of a discussion we had with @uweschaefer and @maciekpapiez: 

- Update docs regarding the current situation 

Then:

- Let snapshot serialisers implement calculateSerialVersionUID (ObjectMapper can easily do this with JsonSchemaGenerator) 
- This is used unless a field annotated with @SnapshotVersion is found
- Query snapshots for classname, serialiser type and serial version
- In case query is empty, recreate from scratch
- In the unlikely case that deserialisation does not work, log warning and also recreate from scratch

**Comment by uweschaefer** [comment]
"In the unlikely case that deserialisation does not work, log warning and also recreate from scratch"

Still wondering if that is a good idea.I'd prefer throw an exception so that the app knows about it and can mitigate by removing snapshot and refetch, or die in a fire...

**Comment by BernhardBln** [comment]
> "In the unlikely case that deserialisation does not work, log warning and also recreate from scratch"
> 
> Still wondering if that is a good idea.I'd prefer throw an exception so that the app knows about it and can mitigate by removing snapshot and refetch, or die in a fire...

I'm sure this will lead to the same outcome, only that the recovery code is then not centralised in factus, but around every line of code that does factus.fetch.

I think a warning is good enough, it shows something is odd, but still allows the code to work as the developers (obviously :P) expected.

**Comment by uweschaefer** [comment]
fine. lets go with that then. if the need comes up, we can make it configurable.

**Comment by uweschaefer** [comment]
closed by #1050
