### ISSUE TITLE
[Factus] Lock on non-existing aggregate leads to exception

### ISSUE THREAD

**Issue by otbe** [factcast/factcast#1041]
Hi,

Imagine something like 
```
factus
        .withLockOn(
            FooAgg.class, UUID.randomUUID())
        .attempt(
            (agg, tx) -> ...)

```

If no event exists (from the FactSpec) that matches the aggregate id then an exception is thrown like:
```
org.factcast.factus.lock.LockedOperationAbortedException: org.factcast.core.lock.AttemptAbortedException: org.factcast.factus.lock.LockedOperationAbortedException: java.lang.NullPointerException: aggregateId is marked non-null but is null
```

I think thats related to https://github.com/factcast/factcast/blob/master/factcast-factus/src/main/java/org/factcast/factus/DefaultFactus.java#L407. The `orElse` calls `instantiate` instead of `initial` and so the `aggregateId` gets lost.

**Comment by uweschaefer** [comment]
Also, when updating the projection on re-attempt, it must be tolerant to non-existing aggregates

**Comment by uweschaefer** [comment]
@otbe  What exactly is the usecase of locking on a non-existent aggregate?

**Comment by otbe** [comment]
Hey @uweschaefer 🤗
I just discovered this small difference in behavior between find/fetch and withLockOn by accident. The former will throw an IllegalStateException the latter the one from above. My usecase was to find the aggregate by id and the id comes from the user (via API)

**Comment by uweschaefer** [comment]
@otbe why not use find instead of fetch in the first place, and then lock on the result if it exists, or not lock at all?
i feel like the patch we're having here is a bit misleading and inconsistent, as 
`fetch(Foo.class, nonExistentId)` will not return, but 
`withLockOn(Foo.class, nonExistentId)` will call the attempt with an initial instance. 

*If* withLockOn for non-existent aggregates needs to work, how about passing null to the attempt instead of faking a non-existent aggregate ?

Regarding the exceptions: i feel like the difference is correct, as withLock promises to throw LockedOperationAbortedException.

**Comment by otbe** [comment]
Dunno 🤷‍♂️ To be clear here: we use find in the first place but multiple of us run into that issue and seemed to be a misleading at some places but it's fine to keep it like this  🤗

**Comment by uweschaefer** [comment]
agreed to close with @otbe
