### ISSUE TITLE
Merge main to master

### ISSUE THREAD

**Issue by BernhardBln** [factcast/factcast#1660]
Due to missing access rights, we currently merge PRs into main, which should be merged into master by @uweschaefer later.

Following PRs are still open but got merged into main (in this order):

- #1632 [merged]
#1655
MR to merge into master: #1671
  
- #1158 [alternative implementation]
#1658
MR to merge into master: #1672

- #1590 [merged]
#1657 
MR to merge into master: #1673

- #1588 [merged]
#1656 
MR to merge into master: #1674

Still waiting for review:

- #1154 [merged]
#1652
 
- #1162 [merged]
  #1663

Waiting for discussion:

- #1169 [alternative implementation]
#1662

**Comment by uweschaefer** [comment]
please keep the PRs open or keep track of the order, so that they can be redirected one by one against master and merged individually.
it would be good if the PRs always fork from master, so that we do not have unnecessary interdependencies that - in the end - leave us with the option to merge all or drop all.

**Comment by BernhardBln** [comment]
We created main to avoid forking from master and then piling up merge conflicts. You can consider main the new master, until you merge it into master. Or consider dropping master and keeping main.

**Comment by uweschaefer** [comment]
i understand but disagree. please keep things separate as long as they do not absolutely necessary rely on each other.
As in any other OSS project, there is a need to carefully review and selectivly merge each feature/fix/change.
