### ISSUE TITLE
Store capabilities should either be published, or store should be accessible from factus/factcast

### ISSUE THREAD

**Issue by uweschaefer** [factcast/factcast#2991]
**Describe the bug**
The FactStore can do useful things like `store.lastSerialBefore(start.toLocalDate())`which is not available from Factus or FactCast.

We should think about either publishing those capabilities on the Factus/factCast interfaces, or at least make the store accessible from Factus/FactCast by adding a getter like `.fastStore()`

**FactCast Server/Client Version**

0.7.8

**Comment by bedaka** [comment]
Since the current implementation of `lastSerialBefore` is a already a workaround, we decided against exposing them directly to the outside.
Instead we'll follow the second approach to make factStore accessible to unblock those who depend on the functionality while making clear that its use is risky.

**Comment by uweschaefer** [comment]
closed by #3010
