### ISSUE TITLE
Integration Test

### ISSUE THREAD

**Issue by uweschaefer** [factcast/factcast#447]
_From @StephanPraetsch on 2019-06-06 13:35:47 +0000 UTC_

**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I have a SpringBoot application without an integration test that covers some general behavior.

**Describe the solution you'd like**
I'd like to know a sensible way how to write an integration test that uses my productive FactCast (same libs and same configuration). For instance I'd like to test
  * Does the application start at all?
  * Does GRPC work with the expected port?
  * Will I receive a just published event?
 
Therefor I think that test must run with a PostgreSQL (instead of a InMemFactstore).

_Copied from original issue: Mercateo/factcast#447_

**Comment by uweschaefer** [comment]
_From @uweschaefer on 2019-06-20 11:59:26 +0000 UTC_

We talked and agreed this is an issue of documentation:

it'd be nice to have a page in factcast-site that walks a user through setting up an integration test that uses testcontainer to run a pgsql and a factcast with pgsql-store before running an integration test.

@StephanPraetsch would you mind writing one?

**Comment by mweirauch** [comment]
The issue is rather about having `factcast-server-grpc` *and* `factcast-client-grpc` (the latter in test scope) in the same project.
Boot will complain that the `FactStore` beans (under the same name) are there. Or more specifically, it doesn't allow bean overwriting since `2.1.x`.

```
The bean 'factStore', defined in class path resource [org/factcast/store/pgsql/internal/PgFactStoreInternalConfiguration.class], could not be registered. A bean with that name has already been defined in class path resource [org/factcast/spring/boot/autoconfigure/client/grpc/GrpcFactStoreAutoConfiguration.class] and overriding is disabled.
```

The same problem would happen if we'd write an integration test against the factcast example servers which are run during the integration-test phase.

Allthough one could argue that the factcast project itself is providing enough tests to make sure that there is no regression, but as we are not delivering a ready-to-use production artifact, I can understand the desire and support in that respect the motivation to run simple integration tests with a factcast GRPC client to ensure the custom-assembled factcast instance mets the expectations of his "creator".

One would need to toy with the Spring (Boot) configurations and see if we can register the beans with different names. (The `InMemFactStore` should be considered when introducing changes.)

**Comment by uweschaefer** [comment]
the idea is to document the use of a proper factcast with pgstore as well as a pg in a testcontainer.

just separating the stores by using named injection to make them usable in one VM is supposedly easy. would that be useful already?

**Comment by uweschaefer** [comment]
@StephanPraetsch would you want to contribute this?

**Comment by uweschaefer** [comment]
@StephanPraetsch still relevant?

**Comment by StephanPraetsch** [comment]
Yes, still relevant. But didnt get time to do this. We can close this issue and I will create a PR independent in this issue as soon as I'm ready to do that. Deal?

**Comment by uweschaefer** [comment]
see modules under factcast-integration-full
